/** All user-facing microcopy (Indonesian). Single source, see docs/06_UI_UX_DESIGN.md section 8. */
export const COPY = {
  appName: 'AcneVision AI',
  disclaimer:
    'Hasil ini merupakan analisis AI dan bukan diagnosis medis. Konsultasikan ke dokter kulit untuk penanganan yang tepat.',
  disclaimerTitle: 'Catatan Penting',
  nav: {
    home: 'Beranda',
    liveDetection: 'Deteksi Langsung',
    howItWorks: 'Cara Kerja',
    about: 'Tentang',
    newAnalysis: 'Analisis Baru',
    history: 'Riwayat',
    consultation: 'Konsultasi',
    login: 'Masuk',
    tryDetection: 'Coba Deteksi',
    profile: 'Profil',
    adminDashboard: 'Dashboard Admin',
    logout: 'Keluar',
    main: 'Navigasi utama',
    openMenu: 'Buka menu',
    closeMenu: 'Tutup menu',
    userMenu: 'Menu akun',
    homeLabel: 'Beranda AcneVision AI',
  },
  footer: {
    tagline: 'Deteksi dan analisis jerawat dari foto wajah dengan bantuan AI.',
    project: 'Proyek mata kuliah Project Teknologi Informasi bersama PT. Dutormasi Membangun Indonesia.',
    navTitle: 'Navigasi',
    accessTitle: 'Akses',
    register: 'Daftar',
    demoNote: 'Aplikasi sedang berjalan dalam mode demo, sehingga hasil yang tampil adalah contoh.',
  },
  home: {
    badge: 'Analisis Kulit Bertenaga AI',
    title: 'Kenali Jerawatmu dengan Lebih Mudah',
    subtitle:
      'Ambil atau unggah foto wajah, lihat lokasi jerawat yang terdeteksi, dan dapatkan gambaran tingkat keparahannya dari jumlah lesi.',
    cta: 'Coba Deteksi',
    guestNote: 'Deteksi awal bisa dicoba tanpa akun.',
    heroAlt: 'Wanita menyentuh pipinya yang memperlihatkan beberapa jerawat kecil',
    lesionTypesTitle: '5 jenis lesi yang dikenali',
    stepsEyebrow: 'Langkah praktis',
    stepsTitle: 'Cara Kerja',
    stepsIntro: 'Tiga langkah sederhana, langsung dari browser.',
    steps: [
      {
        title: 'Ambil atau Unggah Foto',
        text: 'Gunakan kamera perangkat atau unggah foto wajah dari galeri. Pencahayaan yang cukup membantu hasil lebih jelas.',
      },
      {
        title: 'AI Mendeteksi Jerawat',
        text: 'AI menandai lokasi jerawat pada foto dengan kotak dan menghitung jumlah lesi yang terdeteksi.',
      },
      {
        title: 'Lihat Hasil Analisis',
        text: 'Lihat total lesi dan perkiraan tingkat keparahan. Setelah masuk, hasilnya mencakup jenis jerawat.',
      },
    ],
    tiersTitle: 'Tamu dan Akun',
    tiersIntro: 'Coba deteksi dulu tanpa akun. Masuk untuk membuka analisis yang lebih lengkap.',
    guestTitle: 'Tanpa akun',
    guestItems: [
      'Deteksi lokasi jerawat pada foto',
      'Total lesi dan perkiraan tingkat keparahan',
    ],
    memberTitle: 'Dengan akun',
    memberItems: [
      'Jenis jerawat dari 5 kelas beserta tingkat keyakinan AI',
      'Grad-CAM untuk melihat area yang diperhatikan AI',
      'Konsultasi dan rekomendasi perawatan dari asisten AI',
      'Riwayat analisis tersimpan',
    ],
    guestPhotoNote: 'Foto yang dianalisis sebagai tamu tidak disimpan.',
    register: 'Daftar Akun',
    login: 'Sudah punya akun? Masuk',
  },
  close: 'Tutup',
  loginGateChat: 'Masuk untuk bertanya lebih lanjut ke asisten AI',
  loginGateSave:
    'Masuk untuk menyimpan hasil ke riwayat. Setelah masuk, lakukan scan ulang agar hasil tersimpan.',
  loginGateHistory: 'Masuk untuk melihat riwayat analisis kamu',
  noLesion:
    'Tidak ada jerawat terdeteksi. Coba foto ulang dengan pencahayaan lebih terang dan wajah lebih dekat.',
  lowConf: 'AI kurang yakin dengan lesi ini',
  analyzing: 'Menganalisis foto kamu...',
  severityNote: 'Estimasi berdasarkan jumlah lesi yang terdeteksi',
  photoTips: [
    'Pastikan pencahayaan cukup',
    'Wajah terlihat jelas dan menghadap kamera',
    'Jaga kamera tetap stabil',
    'Hindari makeup tebal',
  ],
} as const;
